[package]
name = "colors"
authors = ["flyinsky <flyinksy@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["colors convert"]


[dependencies]
once_cell = "1.17.1"
regex = "1.7.3"
